name = "reminder-bot"
main = "src/index.py"
compatibility_date = "2024-03-07"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "reminder_db"
database_id = "9906564a-48d8-4984-9576-086bf3ef467c"

[triggers]
# 第 1 個是提醒，第 2 個是 16:45 驗證，第 3 個是 05:30 報時
crons = ["* * * * *", "08 09 * * *", "30 21 * * *"]
